# Generated by Django 4.0.2 on 2022-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_season_alter_sighting_options_bird_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='seasons',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
